### ISSUE TITLE
Failing to deploy

### ISSUE THREAD

**Issue by DivineEssentia** [CHollingworth/Lampray#70] opened 2023-11-16 03:12 UTC
**Describe the bug**

After pressing deploy, it gets to step 5 and stops. Terminal output spams `Failed to load XML file` and i have to kill the app, 

**Error message**

Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.
Failed to load XML file.

**To Reproduce**

1. Install a few mods like the ones I have
2. Press deploy
3. watch error log

**Expected behaviour**

mods deploy as expected 

**System Info (please complete the following information):**
 - Linux Flavour: Steam Deck (SteamOS
 - Window Manager: KDE Plasma
 - Lamp Version: 1.0.11

**Additional context**

**Comment by DivineEssentia** [comment] 2023-11-16 03:12
Huh. After trying it like 10 times, it now works right after I submitted the issue. Weird.

**Comment by CHollingworth** [comment] 2023-11-18 21:57
Thats strange, was it a permissions issue. I've heard steamdecks can be tempermental

**Comment by CHollingworth** [comment] 2023-11-18 22:37
ill be marking this as complete for now as i do not know the cause.

**Closed by CHollingworth** 2023-11-18 22:37 UTC
Labels: bug
